### PR TITLE
Add ticket-api specifications from the BOMaaS project

### PR DESCRIPTION
**Pull request by samakinen**
The Ticket API allows the TSP, MaaS-operators and end users to list available ticket products, distribute identities and purchase and deliver the actual ticket products in various formats.

### CODE REVIEW

**Comment by brylie** [comment]
@nighthawk can you take a look at this spec?

**Comment by brylie** [comment]
@maas-alliance/contributors this spec is a candidate for a **0.1** version of the **Ticket API**. Please review, and keep in mind that this is just a step forward (i.e. not "fixed in stone").

**Comment by nighthawk** [comment]
@pomgod , @brylie , I'm confused what happened here. This says "merged" but I can't see it here: https://github.com/maas-alliance/apis/tree/master/specifications

**Comment by brylie** [comment]
Ah this one is kind of funny! It looks like two PRs cancelled each other out. 

1. The initial PR contained two files, `service-registry.yaml` and `ticket.yaml`. 
2. I asked that the PRs be split, so we could review them separately. In the process of splitting, @samakinen deleted one file from each branch. 
3. When the PRs were merged by @pomgod, both files got deleted because of the delete commits.

@samakinen please do the following:

1. create a branch for each file
2. commit each file to its corresponding branch
3. open a separate PR for each branch

That way, we avoid this quantum entanglement wave function collapse twin traveler paradox.

**Pull request merged**
